#!/usr/bin/env bash
set -euo pipefail

: "${AZ_SUBSCRIPTION_ID:?Set AZ_SUBSCRIPTION_ID}"
: "${AZ_RESOURCE_GROUP:?Set AZ_RESOURCE_GROUP}"
: "${AZ_WEBAPP_NAME:?Set AZ_WEBAPP_NAME}"

az account set --subscription "$AZ_SUBSCRIPTION_ID"

az webapp config appsettings set \
  --resource-group "$AZ_RESOURCE_GROUP" \
  --name "$AZ_WEBAPP_NAME" \
  --settings \
    NODE_ENV=production \
    DB_URL="$DB_URL" \
    ACCESS_TOKEN_SECRET="$ACCESS_TOKEN_SECRET" \
    REFRESH_TOKEN_SECRET="$REFRESH_TOKEN_SECRET" \
    CORS_ORIGIN="${CORS_ORIGIN:-}" \
    SESSION_SECRET="${SESSION_SECRET:-}" \
    FRONTEND_URL="${FRONTEND_URL:-}" \
    GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID:-}" \
    GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET:-}" \
    GOOGLE_CALLBACK_URL="${GOOGLE_CALLBACK_URL:-}" \
    DISCORD_CLIENT_ID="${DISCORD_CLIENT_ID:-}" \
    DISCORD_CLIENT_SECRET="${DISCORD_CLIENT_SECRET:-}" \
    DISCORD_CALLBACK_URL="${DISCORD_CALLBACK_URL:-}"
